<?php

use Illuminate\Database\Seeder;

class BrandsTableSeeder extends Seeder {
    
    private $tableName = 'inventory_brands';
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run() {
        
        /* clear dulu */
        DB::table($this->tableName)->delete();
        
        $brands = array(
            array('name'=>'Tanpa Merk'),
            array('name'=>'555'),
            array('name'=>'A3'),
            array('name'=>'Aceclafied'),
            array('name'=>'Acer'),
            array('name'=>'Alfamart'),
            array('name'=>'Alison'),
            array('name'=>'Aqua'),
            array('name'=>'Araldite'),
            array('name'=>'Artline'),
            array('name'=>'Asus'),
            array('name'=>'ATS'),
            array('name'=>'Avx'),
            array('name'=>'Axeel'),
            array('name'=>'Bantex'),
            array('name'=>'Baofeng'),
            array('name'=>'Benex'),
            array('name'=>'Bison'),
            array('name'=>'Bitec'),
            array('name'=>'Black & D'),
            array('name'=>'Borma'),
            array('name'=>'Bosch'),
            array('name'=>'Broco'),
            array('name'=>'Camel'),
            array('name'=>'Canon M100'),
            array('name'=>'Casio'),
            array('name'=>'China'),
            array('name'=>'Dacom'),
            array('name'=>'Dca'),
            array('name'=>'Deli'),
            array('name'=>'Dexsta'),
            array('name'=>'Dextone'),
            array('name'=>'Drekcell'),
            array('name'=>'Dunia Mas'),
            array('name'=>'Ekonomi'),
            array('name'=>'Entena'),
            array('name'=>'Epson'),
            array('name'=>'Essen'),
            array('name'=>'Eterna'),
            array('name'=>'Etona'),
            array('name'=>'Excel'),
            array('name'=>'F75'),
            array('name'=>'Faber'),
            array('name'=>'Fox'),
            array('name'=>'FSK'),
            array('name'=>'GCC'),
            array('name'=>'Genius'),
            array('name'=>'Gold Fox'),
            array('name'=>'Grebel'),
            array('name'=>'Gunindo'),
            array('name'=>'Haier'),
            array('name'=>'Haston'),
            array('name'=>'HP'),
            array('name'=>'Hurica'),
            array('name'=>'Imudex'),
            array('name'=>'IN3106'),
            array('name'=>'Index'),
            array('name'=>'Informa'),
            array('name'=>'Inspiroy'),
            array('name'=>'Joyko'),
            array('name'=>'Kangaro'),
            array('name'=>'Ken Master'),
            array('name'=>'Kenko'),
            array('name'=>'Kiki'),
            array('name'=>'Kin'),
            array('name'=>'Kingstone'),
            array('name'=>'Kingstone Tape'),
            array('name'=>'Kirin'),
            array('name'=>'Korea'),
            array('name'=>'Kris'),
            array('name'=>'Krisbow'),
            array('name'=>'Laba Laba'),
            array('name'=>'Larkin'),
            array('name'=>'Leister'),
            array('name'=>'Lenovo'),
            array('name'=>'LG'),
            array('name'=>'Linex'),
            array('name'=>'Lionstar'),
            array('name'=>'Logitech'),
            array('name'=>'Max'),
            array('name'=>'MDM'),
            array('name'=>'Meiden'),
            array('name'=>'Metabo'),
            array('name'=>'Mimaki'),
            array('name'=>'Molab'),
            array('name'=>'MTM'),
            array('name'=>'Multiopro'),
            array('name'=>'Mutoh'),
            array('name'=>'Nachi Tape'),
            array('name'=>'Nelson'),
            array('name'=>'Neudelan'),
            array('name'=>'Nipon Tape'),
            array('name'=>'Nito'),
            array('name'=>'Ocean'),
            array('name'=>'Onemed'),
            array('name'=>'Panasonic'),
            array('name'=>'Paperline'),
            array('name'=>'Paperone'),
            array('name'=>'Pextons'),
            array('name'=>'Philip'),
            array('name'=>'Piorus'),
            array('name'=>'Post It'),
            array('name'=>'Prohek'),
            array('name'=>'Propan'),
            array('name'=>'Rakitan Intel'),
            array('name'=>'Repil x'),
            array('name'=>'Roland'),
            array('name'=>'Rotring'),
            array('name'=>'Ryu'),
            array('name'=>'Salery'),
            array('name'=>'Samsung'),
            array('name'=>'Samurai Paint'),
            array('name'=>'Sandplex'),
            array('name'=>'Sapord'),
            array('name'=>'SC'),
            array('name'=>'SDI'),
            array('name'=>'Seagate'),
            array('name'=>'Sensi'),
            array('name'=>'Sharp'),
            array('name'=>'Shayu'),
            array('name'=>'Sidu'),
            array('name'=>'Smartfren'),
            array('name'=>'Snowman'),
            array('name'=>'SPC'),
            array('name'=>'SPS'),
            array('name'=>'Staedtier'),
            array('name'=>'Standard'),
            array('name'=>'Stanly'),
            array('name'=>'Stanvik'),
            array('name'=>'Suzuki'),
            array('name'=>'Tangit'),
            array('name'=>'Targus'),
            array('name'=>'Tekiro'),
            array('name'=>'Tiger'),
            array('name'=>'Tokay'),
            array('name'=>'Top'),
            array('name'=>'Toshiba'),
            array('name'=>'Toyo'),
            array('name'=>'TP-LINK'),
            array('name'=>'Turbo'),
            array('name'=>'Type Super'),
            array('name'=>'Ultra'),
            array('name'=>'Uniken'),
            array('name'=>'Uticon'),
            array('name'=>'Velix'),
            array('name'=>'Vezel'),
            array('name'=>'Votre'),
            array('name'=>'Vtec'),
            array('name'=>'WD40'),
            array('name'=>'Wipol'),
            array('name'=>'Workpro 24"'),
            array('name'=>'Xiaomi'),
            array('name'=>'Xinta'),
            array('name'=>'Zebra')
        );

        DB::table($this->tableName)->insert($brands);
    }
}
